@startuml
start
partition 增加用户成长值 {
    if(成长值体系开关开启) then (yes)
        :﻿根据成长值类型查询规则配置;
        if(该成长值类型开启) then (yes)
            if(成长值规则不为空) then (yes)
                :找到成长值业务类型查询对应实现类;
                :实现类中﻿根据成长值规则判断本次应增长的成长值;
                :﻿保存成长值明细;
                :﻿根据成长值和原用户等级校验是否需要晋升平台等级;
                :﻿遍历用户即将增长的等级列表，发放对应的等级券礼包;
                :更新用户的成长值信息及等级信息;
            endif
        endif
    endif
}
stop
@enduml