@startuml
start
:﻿﻿查询快照中的购物清单;
partition ﻿遍历各个店铺下单信息 {
    :﻿组装发票信息;
    partition ﻿验证、包装下单信息 {
        :﻿填充订单基本信息;
        :﻿填充订单商品信息;
        if(分销商品、开店礼包商品) then (yes)
            :不验证起限定量;
        endif
        partition ﻿校验购买商品,计算商品价格 {
            :﻿校验商品库存，删除，上下架状态;
            :﻿﻿验证购买商品的起订量,限定量;
            :﻿﻿填充订单项基本数据;
            :﻿﻿填充订单项区间价;
        }
        #HotPink: 处理分销订单;
        :设置渠道信息、小店名称;
        :﻿商品营销信息冗余,验证,计算,设置各营销优惠,实付金额;
        #HotPink: 处理拼团订单;
        :﻿﻿赠品信息校验与填充;
        partition 计算满系营销、优惠券均摊价，并设置结算信息{
            :设置满系营销商品优惠后的均摊价、结算信息;
            partition 设置店铺优惠券后的均摊价、结算信息{
                :查找出优惠券关联的商品，及总价;
                if(是否达到优惠券使用门槛) then (no)
                    :抛出异常;
                endif
                :如果商品总价小于优惠券优惠金额，设置优惠金额为商品总价;
                :计算均摊价、结算信息;
            }
        }
        partition ﻿﻿计算并设置订单总价(已减去营销优惠总金额){
            :计算商品总价;
            :计算所有营销活动的总优惠金额(非满赠);
            :计算各类营销活动的优惠金额;
            :设置优惠券优惠金额，并追减至优惠总金额;
            :设置优惠总金额、应付金额 = 商品总金额 - 总优惠金额;
        }
        :﻿计算订单原价(追加运费);
    }
}
stop
@enduml
