@startuml
start
partition 验证失效的营销信息(目前包括失效的赠品、满系活动、优惠券) {
    :﻿从订单快照中获取下单时选择的营销、商品信息;
    partition ﻿验证失效赠品、满系活动 {
         partition ﻿﻿校验营销活动 {
            if (﻿营销活动是否被删除、被暂停、未开始或已结束) then (no)
                if (﻿﻿关联商品是否匹配) then (yes)
                    if (﻿﻿用户级别是否满足营销活动设置用户范围)
                    endif
                endif
            endif
        }
        :﻿移除失效的营销活动;
        partition ﻿校验赠品 {
            if(赠品是否被删除、是否上架、是否被禁售或是否有库存)
            endif
        }
        :﻿移除失效的赠品;
        :﻿包装失效的赠品和营销活动的描述信息;
    }
    :﻿将失效内容更新至订单快照;
    partition ﻿验证优惠券 {
        :﻿查询订单使用的、我的未使用的优惠券;
        if(﻿﻿判断订单使用的优惠券是否为我的未使用优惠券)
        endif
        :﻿﻿查看过期优惠券，针对过期的优惠券进行提示;
        :﻿﻿从订单快照中移除过期的优惠券;
    }
}
stop
@enduml
