@startuml

start
if(存在订单组) then (yes)
    :保存订单及订单组信息;
endif
partition 创建订单{
    :﻿校验店铺有效性, 校验店铺支持的发票项;
    :减商品,赠品库存;
    :初始化订单提交状态;
    if(订单审核关闭) then (yes)
        :创建订单开票跟支付单;
    endif
    :查询订单支付顺序设置;
    if(先货后款) then (yes)
        if(订单是否开启订单失效时间设置) then (yes)
            :查询设置中订单超时时间;
            :发送非拼团单取消订单延迟队列;
        endif;
    endif
    if(拼团订单) then (yes)
        :设置订单审核状态为"已审核"、流程状态为"已参团";
        :发送拼团单取消订单延迟队列;
    endif
    :订单入库;
}
:﻿批量修改店铺优惠券状态;
:﻿增加客户积分明细 扣除积分;
:修改通用优惠券状态;
stop

@enduml