@startuml

start
if(﻿开店礼包订单) then (yes)
    :使用市场价;
    :不计算营销;
else
    if(分销订单) then (yes)
        partition 计算分销佣金受益人列表 {
            :查询下单人及其邀请人、店主及其邀请人;
            if(是否自购订单) then (yes)
                :受益人为下单人及其邀请人;
            else
                if(佣金返利优先级) then (邀请人优先)
                    if (下单人有邀请人且是分销员) then (yes)
                      :受益人为邀请人及其邀请人;
                    elseif (在店内购买) then (yes)
                      :受益人为店主及其邀请人;
                    endif
                else (店铺优先)
                    if (在店内购买) then (yes)
                      :受益人为店主及其邀请人;
                    elseif (下单人有邀请人且是分销员) then (yes)
                      :受益人为邀请人及其邀请人;
                    endif
                endif
            endif
            :根据脱钩设置(平级脱钩/高于等级脱钩)处理受益人列表;
        }

        partition 根据受益人列表设置分销相关字段 {
            :设置订单分销商品返利人信息;
            :设置订单返利人合计信息;
            :设置订单分销商品提成人信息;
            :设置订单提成人合计信息;
            :订单总佣金合计;
        }
        :设置渠道信息、小店名称;
    endif
endif
stop

@enduml
