@startuml
start
if (使用了积分) then (no)
  :抛出异常;
elseif (﻿商城积分体系是否开启) then (no)
  :抛出异常;
elseif (﻿会员可用积分是否满足积分抵扣使用值) then (no)
  :抛出异常;
elseif (﻿订单使用积分是否超出积分抵扣限额) then (yes)
  :抛出异常;
else
  :﻿计算积分抵扣均摊价、均摊积分数;
  :﻿计算商品的均摊价（扣除积分抵扣金额）;
  :﻿﻿按店铺分组被均摊的商品，设置各订单积分抵扣金额、积分抵扣数量;
  :重新设置订单总价;
endif
stop
@enduml
