-- MySQL Script generated by MySQL Workbench
-- Tue Apr 11 11:30:54 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema b2b
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema b2b
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `b2b` DEFAULT CHARACTER SET utf8 ;
USE `b2b` ;

-- -----------------------------------------------------
-- Table `b2b`.`goods_cate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b2b`.`goods_cate` (
  `cate_id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '商品分类主键',
  `cate_name` VARCHAR(45) NULL COMMENT '分类名称',
  `cate_parent_id` BIGINT(20) NULL COMMENT '父分类ID',
  `cate_img` VARCHAR(255) NULL COMMENT '分类图片',
  `cate_path` VARCHAR(1000) NOT NULL COMMENT '分类层次路径,例1|01|001',
  `cate_grade` TINYINT NOT NULL COMMENT '分类层级',
  `pin_yin` VARCHAR(45) NULL COMMENT '拼音',
  `s_pin_yin` VARCHAR(45) NULL COMMENT '简拼',
  `create_time` DATETIME NULL COMMENT '创建时间',
  `update_time` DATETIME NULL COMMENT '更新时间',
  `del_flag` TINYINT NULL COMMENT '删除标识,0:未删除1:已删除',
  `sort` TINYINT NULL COMMENT '排序',
  `is_default` TINYINT NULL COMMENT '是否默认,0:否1:是',
  PRIMARY KEY (`cate_id`))
ENGINE = InnoDB
COMMENT = '商品分类表';


-- -----------------------------------------------------
-- Table `b2b`.`goods_brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b2b`.`goods_brand` (
  `brand_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `brand_name` VARCHAR(45) NULL,
  `pin_yin` VARCHAR(45) NULL COMMENT '拼音',
  `s_pin_yin` VARCHAR(45) NULL COMMENT '简拼',
  `create_time` DATETIME NULL COMMENT '创建时间',
  `update_time` DATETIME NULL COMMENT '更新时间',
  `del_flag` TINYINT NULL COMMENT '删除标识,0:未删除1:已删除',
  PRIMARY KEY (`brand_id`))
ENGINE = InnoDB
COMMENT = '商品品牌表';


-- -----------------------------------------------------
-- Table `b2b`.`goods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b2b`.`goods` (
  `goods_id` VARCHAR(32) NOT NULL,
  `cate_id` BIGINT(20) NOT NULL COMMENT '商品分类Id',
  `brand_id` BIGINT(20) NOT NULL COMMENT '品牌Id',
  `goods_name` VARCHAR(255) NOT NULL COMMENT '商品标题',
  `goods_subtitle` VARCHAR(255) NULL COMMENT '商品副标题',
  `goods_no` VARCHAR(45) NOT NULL COMMENT 'SPU编码',
  `goods_unit` VARCHAR(45) NULL COMMENT '计量单位',
  `goods_img` VARCHAR(255) NULL COMMENT '商品主图片',
  `goods_weight` DECIMAL(20,2) NULL COMMENT '商品重量',
  `market_price` DECIMAL(20,2) NULL COMMENT '市场价',
  `cost_price` DECIMAL(20,2) NULL COMMENT '成本价',
  `create_time` DATETIME NULL COMMENT '创建时间',
  `update_time` DATETIME NULL COMMENT '更新时间',
  `added_time` DATETIME NULL COMMENT '上下架时间',
  `del_flag` TINYINT NULL COMMENT '删除标识,0:未删除1:已删除',
  `added_flag` TINYINT NULL COMMENT '上下架状态,0:下架1:上架2:部分上架',
  `more_spec_flag` TINYINT NULL COMMENT '规格类型,0:单规格1:多规格',
  `price_type` TINYINT NULL COMMENT '设价类型,0:按客户1:按订货量',
  `custom_flag` TINYINT NULL COMMENT '按客户单独定价,0:否1:是',
  `level_discount_flag` TINYINT NULL COMMENT '叠加客户等级折扣，0:否1:是',
  `third_id` VARCHAR(32) NULL COMMENT '商家ID',
  `is_third` TINYINT NULL COMMENT '商家标识,0:否1:是',
  `audit_status` TINYINT NULL COMMENT '审核状态,0:未审核1 审核通过2审核失败',
  `audit_reason` VARCHAR(255) NULL COMMENT '审核原因',
  `goods_detail` TEXT NULL COMMENT '商品详情',
  `goods_mobile_detail` TEXT NULL COMMENT '移动端图文详情',
  PRIMARY KEY (`goods_id`),
  UNIQUE INDEX `product_id_UNIQUE` (`goods_id` ASC))
ENGINE = InnoDB
COMMENT = 'SPU表';


-- -----------------------------------------------------
-- Table `b2b`.`goods_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b2b`.`goods_info` (
  `goods_info_id` VARCHAR(32) NOT NULL,
  `goods_id` VARCHAR(32) NOT NULL COMMENT '商品ID',
  `goods_info_name` VARCHAR(255) NOT NULL COMMENT '商品名称',
  `goods_info_no` VARCHAR(45) NOT NULL COMMENT 'SPU编码',
  `goods_info_img` VARCHAR(255) NULL COMMENT 'SPU图片',
  `goods_info_barcode` VARCHAR(45) NULL COMMENT '条形码',
  `stock` BIGINT(10) NULL COMMENT '库存',
  `market_price` DECIMAL(20,2) NULL COMMENT '市场价',
  `cost_price` DECIMAL(20,2) NULL COMMENT '成本价',
  `create_time` DATETIME NULL COMMENT '创建时间',
  `update_time` DATETIME NULL COMMENT '更新时间',
  `added_time` DATETIME NULL COMMENT '上下架时间',
  `del_flag` TINYINT NULL COMMENT '删除标识,0:未删除1:已删除',
  `added_flag` TINYINT NULL COMMENT '上下架状态,0:下架1:上架',
  `third_id` VARCHAR(32) NULL COMMENT '商家ID',
  PRIMARY KEY (`goods_info_id`),
  UNIQUE INDEX `goods_info_id_UNIQUE` (`goods_info_id` ASC),
ENGINE = InnoDB
COMMENT = 'SKU货品表';


-- -----------------------------------------------------
-- Table `b2b`.`goods_image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b2b`.`goods_image` (
  `image_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `goods_id` VARCHAR(32) NULL COMMENT 'SPU编号',
  `goods_info_id` VARCHAR(32) NULL COMMENT 'SKU编号',
  `artwork_url` VARCHAR(255) NULL COMMENT '原图地址',
  `middle_url` VARCHAR(255) NULL COMMENT '中图地址',
  `thumb_url` VARCHAR(255) NULL COMMENT '小图地址',
  `big_url` VARCHAR(255) NULL COMMENT '大图地址',
  `create_time` DATETIME NULL COMMENT '创建时间',
  `update_time` DATETIME NULL COMMENT '更新时间',
  `del_flag` TINYINT NULL COMMENT '删除标识,0:未删除1:已删除',
  PRIMARY KEY (`image_id`))
ENGINE = InnoDB
COMMENT = '商品图片表';


-- -----------------------------------------------------
-- Table `b2b`.`spec`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b2b`.`spec` (
  `spec_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `spec_name` VARCHAR(45) NOT NULL COMMENT '规格名称',
  PRIMARY KEY (`spec_id`))
ENGINE = InnoDB
COMMENT = '规格表';


-- -----------------------------------------------------
-- Table `b2b`.`spec_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b2b`.`spec_detail` (
  `spec_detail_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `spec_id` BIGINT(20) NULL,
  `detail_name` VARCHAR(45) NULL COMMENT '规格值名称',
  PRIMARY KEY (`spec_detail_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b2b`.`goods_spec`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b2b`.`goods_spec` (
  `spec_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `goods_id` VARCHAR(32) NULL COMMENT 'SPU编号',
  `spec_name` VARCHAR(45) NOT NULL COMMENT '规格名称',
  `create_time` DATETIME NULL COMMENT '创建时间',
  `update_time` DATETIME NULL COMMENT '更新时间',
  `del_flag` TINYINT NULL COMMENT '删除标识,0:未删除1:已删除',
  PRIMARY KEY (`spec_id`))
ENGINE = InnoDB
COMMENT = '商品规格关联表';


-- -----------------------------------------------------
-- Table `b2b`.`goods_spec_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b2b`.`goods_spec_detail` (
  `spec_detail_id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '规格值ID',
  `goods_id` VARCHAR(32) NOT NULL COMMENT 'SPU编号',
  `spec_id` BIGINT(20) NOT NULL COMMENT '规格ID',
  `detail_name` VARCHAR(45) NOT NULL COMMENT '规格值名称',
  `create_time` DATETIME NULL COMMENT '创建时间',
  `update_time` DATETIME NULL COMMENT '更新时间',
  `del_flag` TINYINT NULL COMMENT '删除标识,0:未删除1:已删除',
  PRIMARY KEY (`spec_detail_id`))
ENGINE = InnoDB
COMMENT = ' 商品规格值关联表';


-- -----------------------------------------------------
-- Table `b2b`.`goods_info_spec_detail_rel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b2b`.`goods_info_spec_detail_rel` (
  `spec_detail_rel_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `goods_id` VARCHAR(32) NOT NULL COMMENT 'SPU编号',
  `goods_info_id` VARCHAR(32) NOT NULL COMMENT 'SKU编号',
  `spec_detail_id` BIGINT(20) NOT NULL,
  `spec_id` BIGINT(20) NOT NULL COMMENT '规格ID',
  `detail_name` VARCHAR(45) NULL COMMENT ' 规格值名称',
  `create_time` DATETIME NULL COMMENT '创建时间',
  `update_time` DATETIME NULL COMMENT '更新时间',
  `del_flag` TINYINT NULL COMMENT '删除标识,0:未删除1:已删除',
  PRIMARY KEY (`spec_detail_rel_id`))
ENGINE = InnoDB
COMMENT = 'SKU与规格值关联表';


-- -----------------------------------------------------
-- Table `b2b`.`goods_level_price`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b2b`.`goods_level_price` (
  `level_price_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `goods_id` VARCHAR(32) NOT NULL COMMENT 'SPU编号',
  `level_id` BIGINT(20) NOT NULL COMMENT '客户等级ID',
  `price` DECIMAL(20,2) NULL COMMENT '订货价',
  `count` BIGINT(10) NULL COMMENT '起订量',
  `max_count` BIGINT(10) NULL COMMENT '限定量',
  `goods_info_id` VARCHAR(32) NULL COMMENT 'SKU编号',
  `type` TINYINT NOT NULL COMMENT '0:spu,1:sku',
  PRIMARY KEY (`level_price_id`))
ENGINE = InnoDB
COMMENT = '商品级别价格表';


-- -----------------------------------------------------
-- Table `b2b`.`goods_customer_price`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b2b`.`goods_customer_price` (
  `customer_price_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `goods_id` VARCHAR(32) NOT NULL COMMENT 'SPU编号',
  `customer_id` VARCHAR(32) NOT NULL COMMENT '客户ID',
  `price` DECIMAL(20,2) NULL COMMENT '订货价',
  `count` BIGINT(10) NULL COMMENT '起订量',
  `max_count` BIGINT(10) NULL COMMENT '限定量',
  `goods_info_id` VARCHAR(32) NULL COMMENT 'SKU编号',
  `type` TINYINT NOT NULL COMMENT '0:spu,1:sku',
  PRIMARY KEY (`customer_price_id`))
ENGINE = InnoDB
COMMENT = '商品客户价格表';


-- -----------------------------------------------------
-- Table `b2b`.`goods_interval_price`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b2b`.`goods_interval_price` (
  `interval_price_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `goods_id` VARCHAR(32) NOT NULL COMMENT 'SPU编号',
  `count` BIGINT(10) NULL COMMENT '订货区间',
  `price` DECIMAL(20,2) NULL COMMENT '订货价',
  `goods_info_id` VARCHAR(32) NULL COMMENT 'SKU编号',
  `type` TINYINT NOT NULL COMMENT '0:spu,1:sku',
  PRIMARY KEY (`interval_price_id`))
ENGINE = InnoDB
COMMENT = '商品订货区间价格表';


-- -----------------------------------------------------
-- Table `b2b`.`goods_customer_follow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b2b`.`goods_customer_follow` (
  `follow_id` BIGINT NOT NULL AUTO_INCREMENT,
  `third_id` VARCHAR(32) NULL COMMENT '商家ID',
  `customer_id` VARCHAR(32) NOT NULL COMMENT '会员Id',
  `goods_id` VARCHAR(32) NOT NULL COMMENT '商品Id',
  `goods_info_id` VARCHAR(32) NOT NULL COMMENT 'SKU编号',
  `create_time` DATETIME NOT NULL COMMENT '创建时间',
  `goods_num` BIGINT(10) NOT NULL COMMENT '购买数',
  `follow_flag` TINYINT NULL COMMENT '收藏标识0:all,1.采购,2:收藏',
  PRIMARY KEY (`follow_id`))
ENGINE = InnoDB
COMMENT = '商品的客户收藏';


-- -----------------------------------------------------
-- Table `b2b`.`goods_customer_num`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b2b`.`goods_customer_num` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `customer_id` VARCHAR(32) NOT NULL COMMENT '会员编号',
  `goods_info_id` VARCHAR(32) NOT NULL COMMENT 'SKU编号',
  `goods_num` BIGINT(10) NOT NULL COMMENT '购买数',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '商品的客户全局购买数(暂时无用)';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
