-- MySQL Script generated by MySQL Workbench
-- Mon May 15 13:41:57 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema b2b
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema b2b
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `b2b` DEFAULT CHARACTER SET utf8 ;
USE `b2b` ;

-- -----------------------------------------------------
-- Table `b2b`.`system_image_cate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b2b`.`system_image_cate` (
  `cate_id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '商品分类主键',
  `cate_name` VARCHAR(45) NULL COMMENT '分类名称',
  `cate_parent_id` BIGINT(20) NULL COMMENT '父分类ID',
  `cate_img` VARCHAR(255) NULL COMMENT '分类图片',
  `cate_path` VARCHAR(1000) NOT NULL COMMENT '分类层次路径,例1|01|001',
  `cate_grade` TINYINT NOT NULL COMMENT '分类层级',
  `pin_yin` VARCHAR(45) NULL COMMENT '拼音',
  `s_pin_yin` VARCHAR(45) NULL COMMENT '简拼',
  `create_time` DATETIME NULL COMMENT '创建时间',
  `update_time` DATETIME NULL COMMENT '更新时间',
  `del_flag` TINYINT NULL COMMENT '删除标识,0:未删除1:已删除',
  `sort` TINYINT NULL COMMENT '排序',
  `is_default` TINYINT NULL COMMENT '是否默认,0:否1:是',
  PRIMARY KEY (`cate_id`))
ENGINE = InnoDB
COMMENT = '图片分类表';


-- -----------------------------------------------------
-- Table `b2b`.`system_image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b2b`.`system_image` (
  `image_id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '图片ID',
  `cate_id` BIGINT(20) NOT NULL COMMENT '图片分类ID',
  `image_key` VARCHAR(255) NULL COMMENT '图片KEY',
  `image_name` VARCHAR(45) NULL COMMENT ' 图片名称',
  `artwork_url` VARCHAR(255) NULL COMMENT '原图地址',
  `create_time` DATETIME NULL COMMENT '创建时间',
  `update_time` DATETIME NULL COMMENT '更新时间',
  `del_flag` TINYINT NULL COMMENT '删除标识,0:未删除1:已删除',
  `server_type` VARCHAR(255) NULL COMMENT '图片服务器类型，对应system_config的config_type',
  PRIMARY KEY (`image_id`))
ENGINE = InnoDB
COMMENT = '图片表';


-- -----------------------------------------------------
-- Table `b2b`.`system_config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b2b`.`system_config` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT ' 编号',
  `config_key` VARCHAR(255) NOT NULL COMMENT '键',
  `config_type` VARCHAR(255) NOT NULL COMMENT '类型',
  `config_name` VARCHAR(255) NOT NULL COMMENT '名称',
  `remark` VARCHAR(255) NULL COMMENT '备注',
  `status` TINYINT(1) NULL COMMENT '状态,0:未启用1:已启用',
  `context` LONGTEXT NULL COMMENT '配置内容，如JSON内容',
  `create_time` DATETIME NULL COMMENT '创建时间',
  `update_time` DATETIME NULL COMMENT '更新时间',
  `del_flag` TINYINT NULL COMMENT '删除标识,0:未删除1:已删除',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
COMMENT = '系统配置表';


-- -----------------------------------------------------
-- Table `b2b`.`system_operation_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b2b`.`system_operation_log` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `op_name` VARCHAR(128) NULL COMMENT '操作人',
  `op_code` VARCHAR(100) NULL COMMENT '操作关键字',
  `op_context` VARCHAR(255) NULL COMMENT '操作内容',
  `op_time` DATETIME NULL COMMENT '操作时间',
  `op_ip` VARCHAR(50) NULL COMMENT '操作IP',
  `op_mac` VARCHAR(255) NULL COMMENT '操作MAC地址',
  `op_isp` VARCHAR(255) NULL COMMENT '运营商',
  `third_id` VARCHAR(255) NULL COMMENT '第三方ID',
  `op_country` VARCHAR(45) NULL COMMENT '所在国家',
  `op_province` VARCHAR(45) NULL COMMENT '所在省份',
  `op_city` VARCHAR(45) NULL COMMENT '所在城市',
  `employee_id` VARCHAR(32) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '操作日志';


-- -----------------------------------------------------
-- Table `b2b`.`system_ip_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b2b`.`system_ip_info` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `ip` VARCHAR(50) NULL DEFAULT NULL COMMENT 'IP',
  `isp` VARCHAR(255) NULL DEFAULT NULL COMMENT '运营商',
  `country` VARCHAR(45) NULL DEFAULT NULL COMMENT '国家',
  `province` VARCHAR(45) NULL DEFAULT NULL COMMENT '省份',
  `city` VARCHAR(45) NULL DEFAULT NULL COMMENT '城市',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'IP归属信息';


-- -----------------------------------------------------
-- Table `b2b`.`base_config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b2b`.`base_config` (
  `base_config_id` INT NOT NULL AUTO_INCREMENT COMMENT '基本设置ID',
  `pc_website` VARCHAR(128) NULL COMMENT 'PC端商城网址',
  `mobile_website` VARCHAR(128) NULL COMMENT '移动端商城网址',
  `pc_logo` VARCHAR(128) NULL COMMENT 'PC商城logo',
  `pc_banner` VARCHAR(500) NULL COMMENT 'PC商城banner,最多可添加5个,多个图片间以"|"隔开',
  `mobile_banner` VARCHAR(500) NULL COMMENT '移动商城banner,最多可添加5个,多个图片间以"|"隔开',
  PRIMARY KEY (`base_config_id`))
ENGINE = InnoDB
COMMENT = '基本设置'


-- -----------------------------------------------------
-- Table `b2b`.`company_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b2b`.`company_info` (
  `company_info_id` INT NOT NULL AUTO_INCREMENT COMMENT '公司信息ID',
  `company_name` VARCHAR(255) NULL COMMENT '公司名称',
  `province_id` BIGINT(10) NULL COMMENT '省',
  `city_id` BIGINT(10) NULL COMMENT '市',
  `area_id` BIGINT(10) NULL COMMENT '区',
  `detail_address` VARCHAR(255) NULL COMMENT '详细地址',
  `contact_name` VARCHAR(128) NULL COMMENT '联系人',
  `contact_phone` VARCHAR(13) NULL COMMENT '联系方式',
  `copyright` VARCHAR(255) NULL COMMENT '版权信息',
  `company_descript` VARCHAR(255) NULL COMMENT '公司简介',
  `operator` VARCHAR(45) NULL COMMENT '操作人',
  `create_time` DATETIME NULL COMMENT '创建时间',
  `update_time` DATETIME NULL COMMENT '修改时间',
  PRIMARY KEY (`company_info_id`))
ENGINE = InnoDB
COMMENT = '公司信息'


CREATE TABLE IF NOT EXISTS `b2b`.`express_company` (
  `express_company_id` BIGINT(5) NOT NULL AUTO_INCREMENT COMMENT '主键ID,自增',
  `express_name` VARCHAR(125) NULL COMMENT '物流公司名称',
  `express_code` VARCHAR(255) NULL COMMENT '物流公司代码',
  `is_checked` TINYINT(1) NULL COMMENT '是否是常用物流公司 0：否 1：是',
  `is_add` tinyint(1) DEFAULT NULL COMMENT '是否是用户新增 0：否 1：是',
  PRIMARY KEY (`express_company_id`))
ENGINE = InnoDB
COMMENT = '物流公司';


INSERT into express_company(express_name, express_code, is_checked, is_add)VALUES ('顺丰速递','shunfeng',0, 0);
INSERT into express_company(express_name, express_code, is_checked, is_add)VALUES ('申通快递','shentong',0, 0);
INSERT into express_company(express_name, express_code, is_checked, is_add)VALUES ('中通快递','zhongtong',0, 0);
INSERT into express_company(express_name, express_code, is_checked, is_add)VALUES ('圆通速递','yuantong',0, 0);
INSERT into express_company(express_name, express_code, is_checked, is_add)VALUES ('国通快递','guotongkuaidi',0, 0);
INSERT into express_company(express_name, express_code, is_checked, is_add)VALUES ('汇通快递','huitongkuaidi',0, 0);
INSERT into express_company(express_name, express_code, is_checked, is_add)VALUES ('韵达快递','yunda',0, 0);
INSERT into express_company(express_name, express_code, is_checked, is_add)VALUES ('天天快递','tiantian',0, 0);
INSERT into express_company(express_name, express_code, is_checked, is_add)VALUES ('全峰快递','quanfengkuaidi',0, 0);
INSERT into express_company(express_name, express_code, is_checked, is_add)VALUES ('百世物流','baishiwuliu',0, 0);
INSERT into express_company(express_name, express_code, is_checked, is_add)VALUES ('中国邮政','youzhengguonei',0, 0);
INSERT into express_company(express_name, express_code, is_checked, is_add)VALUES ('EMS','ems',0, 0);
INSERT into express_company(express_name, express_code, is_checked, is_add)VALUES ('广东EMS','guangdongyouzhengwuliu',0, 0);
INSERT into express_company(express_name, express_code, is_checked, is_add)VALUES ('德邦物流','debangwuliu',0, 0);
INSERT into express_company(express_name, express_code, is_checked, is_add)VALUES ('联邦快递','lianbangkuaidi',0, 0);
INSERT into express_company(express_name, express_code, is_checked, is_add)VALUES ('全一快递','quanyikuaidi',0, 0);
INSERT into express_company(express_name, express_code, is_checked, is_add)VALUES ('安信达快递','anxindakuaixi',0, 0);
INSERT into express_company(express_name, express_code, is_checked, is_add)VALUES ('宅急送','zhaijisong',0, 0);
INSERT into express_company(express_name, express_code, is_checked, is_add)VALUES ('亚风','yafengsudi',0, 0);
INSERT into express_company(express_name, express_code, is_checked, is_add)VALUES ('美国速递','meiguokuaidi',0, 0);
INSERT into express_company(express_name, express_code, is_checked, is_add)VALUES ('能达速递','ganzhongnengda',0, 0);
INSERT into express_company(express_name, express_code, is_checked, is_add)VALUES ('佳吉快递','jiajiwuliu',0, 0);
INSERT into express_company(express_name, express_code, is_checked, is_add)VALUES ('联昊通','lianhaowuliu',0, 0);
INSERT into express_company(express_name, express_code, is_checked, is_add)VALUES ('一邦物流','yibangwuliu',0, 0);
INSERT into express_company(express_name, express_code, is_checked, is_add)VALUES ('龙邦速递','longbanwuliu',0, 0);
INSERT into express_company(express_name, express_code, is_checked, is_add)VALUES ('速尔','suer',0, 0);
INSERT into express_company(express_name, express_code, is_checked, is_add)VALUES ('天地华宇','tiandihuayu',0, 0);
INSERT into express_company(express_name, express_code, is_checked, is_add)VALUES ('飞远配送','feiyuanvipshop',0, 0);
INSERT into express_company(express_name, express_code, is_checked, is_add)VALUES ('优速快递','youshuwuliu',0, 0);
INSERT into express_company(express_name, express_code, is_checked, is_add)VALUES ('新邦物流','xinbangwuliu',0, 0);
INSERT into express_company(express_name, express_code, is_checked, is_add)VALUES ('信丰物流','xinfengwuliu',0, 0);
INSERT into express_company(express_name, express_code, is_checked, is_add)VALUES ('长宇','changyuwuliu',0, 0);
INSERT into express_company(express_name, express_code, is_checked, is_add)VALUES ('大田','datianwuliu',0, 0);
INSERT into express_company(express_name, express_code, is_checked, is_add)VALUES ('中铁快运','zhongtiewuliu',0, 0);
INSERT into express_company(express_name, express_code, is_checked, is_add)VALUES ('增益速递','zengyisudi',0, 0);
INSERT into express_company(express_name, express_code, is_checked, is_add)VALUES ('快捷快递','kuaijiesudi',0, 0);
INSERT into express_company(express_name, express_code, is_checked, is_add)VALUES ('飞远(爱彼西)配送','feiyuanvipshop',0, 0);
INSERT into express_company(express_name, express_code, is_checked, is_add)VALUES ('如风达','rufengda',0, 0);
INSERT into express_company(express_name, express_code, is_checked, is_add)VALUES ('通和天下','tonghetianxia',0, 0);
INSERT into express_company(express_name, express_code, is_checked, is_add)VALUES ('全日通','quanritongkuaidi',0, 0);
INSERT into express_company(express_name, express_code, is_checked, is_add)VALUES ('凤凰','fenghuangkuaidi',0, 0);
INSERT into express_company(express_name, express_code, is_checked, is_add)VALUES ('京广','jinguangsudikuaijian',0, 0);
INSERT into express_company(express_name, express_code, is_checked, is_add)VALUES ('盛辉','shenghuiwuliu',0, 0);
INSERT into express_company(express_name, express_code, is_checked, is_add)VALUES ('万家','wanjiawuliu',0, 0);
INSERT into express_company(express_name, express_code, is_checked, is_add)VALUES ('佳怡','jiayiwuliu',0, 0);
INSERT into express_company(express_name, express_code, is_checked, is_add)VALUES ('越丰','yuefengwuliu',0, 0);
INSERT into express_company(express_name, express_code, is_checked, is_add)VALUES ('宅急便','zhaijibian',0, 0);
INSERT into express_company(express_name, express_code, is_checked, is_add)VALUES ('运通中港','yuntongkuaidi',0, 0);
INSERT into express_company(express_name, express_code, is_checked, is_add)VALUES ('万象','wanxiangwuliu',0, 0);
INSERT into express_company(express_name, express_code, is_checked, is_add)VALUES ('递四方','disifang',0, 0);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
