-- MySQL Script generated by MySQL Workbench
-- Mon Apr 24 15:06:09 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema b2b
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema b2b
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `b2b` DEFAULT CHARACTER SET utf8 ;
USE `b2b` ;

-- -----------------------------------------------------
-- Table `b2b`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b2b`.`customer` ;

CREATE TABLE IF NOT EXISTS `b2b`.`customer` (
  `customer_id` VARCHAR(32) NOT NULL COMMENT '会员标识UUID',
  `customer_level_id` BIGINT(10) NOT NULL COMMENT '客户级别',
  `customer_account` VARCHAR(20) NOT NULL COMMENT '会员登录账号|手机号',
  `customer_password` VARCHAR(200) NOT NULL COMMENT '会员登录密码',
  `customer_salt_val` VARCHAR(200) NULL COMMENT '盐值,用于密码加密',
  `customer_type` TINYINT NULL COMMENT '客户类型  0：运营商 1：经销商 2：零售商',
  `check_state` TINYINT NOT NULL COMMENT '账户的审核状态 0:待审核 1:已审核通过 2:审核未通过',
  `del_flag` TINYINT NOT NULL COMMENT '是否删除标志 0：否，1：是',
  `login_ip` VARCHAR(32) NULL DEFAULT '0.0.0.0' COMMENT '登录IP',
  `login_time` DATETIME NULL COMMENT '登录时间',
  `login_error_time` INT NULL COMMENT '登录错误次数',
  `create_time` DATETIME NULL COMMENT '创建时间|注册时间',
  `create_person` VARCHAR(32) NULL COMMENT '创建人',
  `update_time` DATETIME NULL COMMENT '修改时间',
  `update_person` VARCHAR(32) NULL COMMENT '修改人',
  `delete_time` DATETIME NULL COMMENT '删除时间',
  `delete_person` VARCHAR(32) NULL COMMENT '删除人',
  `login_lock_time` DATETIME NULL COMMENT '登录锁定时间',
  PRIMARY KEY (`customer_id`),
  UNIQUE INDEX `customer_id_UNIQUE` (`customer_id` ASC),
  UNIQUE INDEX `customer_account_UNIQUE` (`customer_account` ASC))
ENGINE = InnoDB
COMMENT = '客户信息表';


-- -----------------------------------------------------
-- Table `b2b`.`customer_level`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b2b`.`customer_level` ;

CREATE TABLE IF NOT EXISTS `b2b`.`customer_level` (
  `customer_level_id` BIGINT(10) NOT NULL AUTO_INCREMENT COMMENT '客户等级ID',
  `customer_level_name` VARCHAR(45) NOT NULL COMMENT '客户等级名称',
  `customer_level_discount` DECIMAL(5,2) NOT NULL COMMENT '客户等级折扣',
  `is_defalt` TINYINT NOT NULL COMMENT '是否是默认等级  0：否，1：是',
  `del_flag` TINYINT NOT NULL COMMENT '是否删除标志 0：否，1：是',
  `create_time` DATETIME NULL COMMENT '创建时间',
  `create_person` VARCHAR(32) NULL COMMENT '创建人',
  `update_time` DATETIME NULL COMMENT '修改时间',
  `update_person` VARCHAR(32) NULL COMMENT '修改人',
  `delete_time` DATETIME NULL COMMENT '删除时间',
  `delete_person` VARCHAR(32) NULL COMMENT '删除人',
  PRIMARY KEY (`customer_level_id`),
  UNIQUE INDEX `customer_level_id_UNIQUE` (`customer_level_id` ASC))
ENGINE = InnoDB
COMMENT = '客户等级表';


-- -----------------------------------------------------
-- Table `b2b`.`customer_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b2b`.`customer_detail` ;

CREATE TABLE IF NOT EXISTS `b2b`.`customer_detail` (
  `customer_detail_id` VARCHAR(32) NOT NULL COMMENT '会员详细信息标识UUID',
  `customer_id` VARCHAR(32) NOT NULL COMMENT '会员ID',
  `customer_name` VARCHAR(128) NULL COMMENT '会员名称',
  `province_id` BIGINT(10) NULL COMMENT '省份',
  `city_id` BIGINT(10) NULL COMMENT '市',
  `area_id` BIGINT(10) NULL COMMENT '区',
  `customer_address` VARCHAR(225) NULL COMMENT '详细街道地址',
  `del_flag` TINYINT NULL COMMENT '是否删除标志 0：否，1：是',
  `customer_status` TINYINT NULL COMMENT '账号状态 0：启用中  1：禁用中',
  `contact_name` VARCHAR(128) NULL COMMENT '联系人名字',
  `contact_phone` VARCHAR(20) NULL COMMENT '联系方式',
  `employee_id` VARCHAR(32) NULL COMMENT '负责业务员',
  `create_time` DATETIME NULL COMMENT '创建时间',
  `create_person` VARCHAR(32) NULL COMMENT '创建人',
  `update_time` DATETIME NULL COMMENT '修改时间',
  `update_person` VARCHAR(32) NULL COMMENT '修改人',
  `delete_time` DATETIME NULL COMMENT '删除时间',
  `delete_person` VARCHAR(32) NULL COMMENT '删除人',
  PRIMARY KEY (`customer_detail_id`),
  UNIQUE INDEX `customer_detail_id_UNIQUE` (`customer_detail_id` ASC))
ENGINE = InnoDB
COMMENT = '客户详细信息';


-- -----------------------------------------------------
-- Table `b2b`.`customer_account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b2b`.`customer_account` ;

CREATE TABLE IF NOT EXISTS `b2b`.`customer_account` (
  `customer_account_id` VARCHAR(32) NOT NULL COMMENT '客户银行账号ID',
  `customer_id` VARCHAR(32) NOT NULL COMMENT '会员标识UUID',
  `customer_account_name` VARCHAR(128) NOT NULL COMMENT '账户名字',
  `customer_account_no` VARCHAR(30) NOT NULL COMMENT '银行账号',
  `customer_bank_name` VARCHAR(128) NOT NULL COMMENT '开户行',
  `del_flag` TINYINT NOT NULL COMMENT '是否删除标志 0：否，1：是',
  `create_time` DATETIME NULL COMMENT '创建时间',
  `create_person` VARCHAR(32) NULL COMMENT '创建人',
  `update_time` DATETIME NULL COMMENT '修改时间',
  `update_person` VARCHAR(32) NULL COMMENT '修改人',
  `delete_time` DATETIME NULL COMMENT '删除时间',
  `delete_person` VARCHAR(32) NULL COMMENT '删除人',
  PRIMARY KEY (`customer_account_id`),
  UNIQUE INDEX `customer_account_id_UNIQUE` (`customer_account_id` ASC))
ENGINE = InnoDB
COMMENT = '客户的银行账号';


-- -----------------------------------------------------
-- Table `b2b`.`customer_invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b2b`.`customer_invoice` ;

CREATE TABLE IF NOT EXISTS `b2b`.`customer_invoice` (
  `customer_invoice_id` BIGINT(10) NOT NULL AUTO_INCREMENT COMMENT '增专资质ID',
  `customer_id` VARCHAR(32) NOT NULL COMMENT '会员ID',
  `company_name` VARCHAR(225) NULL COMMENT '单位全称',
  `taxpayer_number` VARCHAR(45) NULL COMMENT '纳税人识别号',
  `company_phone` VARCHAR(20) NULL COMMENT '单位电话',
  `company_address` VARCHAR(225) NULL COMMENT '单位地址',
  `bank_no` VARCHAR(45) NULL COMMENT '银行基本户号',
  `bank_name` VARCHAR(128) NULL COMMENT '开户行',
  `business_license_img` VARCHAR(128) NULL COMMENT '营业执照复印件',
  `taxpayer_identification_img` VARCHAR(128) NULL COMMENT '一般纳税人认证资格复印件',
  `check_state` TINYINT NULL COMMENT '增票资质审核状态  0:待审核 1:已审核通过 2:审核未通过',
  `invalid_flag` TINYINT NULL COMMENT '增专资质是否作废 0：否 1：是',
  `del_flag` TINYINT NULL COMMENT '是否删除标志 0：否，1：是',
  `create_time` DATETIME NULL COMMENT '创建时间',
  `create_person` VARCHAR(32) NULL COMMENT '创建人',
  `update_time` DATETIME NULL COMMENT '修改时间',
  `update_person` VARCHAR(32) NULL COMMENT '修改人',
  `delete_time` DATETIME NULL COMMENT '删除时间',
  `delete_person` VARCHAR(32) NULL COMMENT '删除人',
  PRIMARY KEY (`customer_invoice_id`),
  UNIQUE INDEX `customer_invoice_id_UNIQUE` (`customer_invoice_id` ASC))
ENGINE = InnoDB
COMMENT = '客户开票信息';


-- -----------------------------------------------------
-- Table `b2b`.`customer_delivery_address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b2b`.`customer_delivery_address` ;

CREATE TABLE IF NOT EXISTS `b2b`.`customer_delivery_address` (
  `delivery_address_id` VARCHAR(32) NOT NULL COMMENT '收货地址ID',
  `customer_id` VARCHAR(32) NULL COMMENT '会员ID',
  `consignee_name` VARCHAR(128) NULL COMMENT '收货人',
  `consignee_number` VARCHAR(20) NULL COMMENT '收货人手机号码',
  `province_id` BIGINT(10) NULL COMMENT '省份',
  `city_id` BIGINT(10) NULL COMMENT '市',
  `area_id` BIGINT(10) NULL COMMENT '区',
  `delivery_address` VARCHAR(225) NULL COMMENT '详细街道地址',
  `is_defalt_address` TINYINT NULL COMMENT '是否是默认地址',
  `del_flag` TINYINT NULL COMMENT '是否删除标志 0：否，1：是',
  `create_time` DATETIME NULL COMMENT '创建时间',
  `create_person` VARCHAR(32) NULL COMMENT '创建人',
  `update_time` DATETIME NULL COMMENT '修改时间',
  `update_person` VARCHAR(32) NULL COMMENT '修改人',
  `delete_time` DATETIME NULL COMMENT '删除时间',
  `delete_person` VARCHAR(32) NULL COMMENT '删除人',
  PRIMARY KEY (`delivery_address_id`),
  UNIQUE INDEX `delivery_address_id_UNIQUE` (`delivery_address_id` ASC))
ENGINE = InnoDB
COMMENT = '客户收货地址表';


-- -----------------------------------------------------
-- Table `b2b`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b2b`.`employee` ;

CREATE TABLE IF NOT EXISTS `b2b`.`employee` (
  `employee_id` VARCHAR(32) NOT NULL COMMENT '员工信息ID',
  `employee_name` VARCHAR(45) NOT NULL COMMENT '员工姓名',
  `employee_mobile` VARCHAR(20) NOT NULL COMMENT '员工手机号',
  `role_id` BIGINT(10) NULL COMMENT '员工角色',
  `is_employee` TINYINT NOT NULL COMMENT '是否业务员 0：是   1：否',
  `account_name` VARCHAR(45) NOT NULL COMMENT '账户名',
  `account_password` VARCHAR(45) NOT NULL COMMENT '账户密码',
  `employee_salt_val` VARCHAR(200) NULL COMMENT '盐值,用于密码加密',
  `account_state` TINYINT NOT NULL COMMENT '账户状态  0：启用   1：禁用',
  `third_id` VARCHAR(32) NULL COMMENT '第三方店铺ID',
  `customer_id` VARCHAR(32) NULL COMMENT '会员编号',
  `del_flag` TINYINT NOT NULL COMMENT '是否删除标志 0：否，1：是',
  `create_time` DATETIME NULL COMMENT '创建时间',
  `create_person` VARCHAR(32) NULL COMMENT '创建人',
  `login_error_time` TINYINT NULL COMMENT '错误登录次数',
  `login_lock_time` DATETIME NULL COMMENT '登录锁定时间',
  `login_time` DATETIME NULL COMMENT '登录时间',
  `update_time` DATETIME NULL COMMENT '修改时间',
  `update_person` VARCHAR(32) NULL COMMENT '修改人',
  `delete_time` DATETIME NULL COMMENT '删除时间',
  `delete_person` VARCHAR(32) NULL COMMENT '删除人',
  PRIMARY KEY (`employee_id`),
  UNIQUE INDEX `employee_id_UNIQUE` (`employee_id` ASC))
ENGINE = InnoDB
COMMENT = '员工信息表';


-- -----------------------------------------------------
-- Table `b2b`.`role_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b2b`.`role_info` ;

CREATE TABLE IF NOT EXISTS `b2b`.`role_info` (
  `role_info_id` BIGINT(10) NOT NULL AUTO_INCREMENT COMMENT '角色ID',
  `role_name` VARCHAR(45) NOT NULL COMMENT '角色名称',
  `role_description` VARCHAR(45) NULL COMMENT '角色描述',
  `del_flag` TINYINT NOT NULL COMMENT '是否删除标志 0：否，1：是',
  `create_time` DATETIME NULL COMMENT '创建时间',
  `create_person` VARCHAR(32) NULL COMMENT '创建人',
  `update_time` DATETIME NULL COMMENT '修改时间',
  `update_person` VARCHAR(32) NULL COMMENT '修改人',
  `delete_time` DATETIME NULL COMMENT '删除时间',
  `delete_person` VARCHAR(32) NULL COMMENT '删除人',
  PRIMARY KEY (`role_info_id`),
  UNIQUE INDEX `role_info_id_UNIQUE` (`role_info_id` ASC))
ENGINE = InnoDB
COMMENT = '角色表';


-- -----------------------------------------------------
-- Table `b2b`.`privilege_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b2b`.`privilege_info` ;

CREATE TABLE IF NOT EXISTS `b2b`.`privilege_info` (
  `privilege_id` VARCHAR(45) NOT NULL COMMENT '权限ID',
  `privilege_name` VARCHAR(45) NOT NULL COMMENT '权限名称',
  `menu_id` VARCHAR(45) NOT NULL COMMENT '对应的菜单ID',
  PRIMARY KEY (`privilege_id`),
  UNIQUE INDEX `privilege_id_UNIQUE` (`privilege_id` ASC))
ENGINE = InnoDB
COMMENT = '权限表';


-- -----------------------------------------------------
-- Table `b2b`.`menu_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b2b`.`menu_info` ;

CREATE TABLE IF NOT EXISTS `b2b`.`menu_info` (
  `menu_id` VARCHAR(45) NOT NULL COMMENT '菜单ID',
  `menu_name` VARCHAR(45) NOT NULL COMMENT '菜单名称',
  `menu_path` VARCHAR(45) NULL COMMENT '前端路由路径',
  PRIMARY KEY (`menu_id`),
  UNIQUE INDEX `menu_id_UNIQUE` (`menu_id` ASC))
ENGINE = InnoDB
COMMENT = '菜单表';


-- -----------------------------------------------------
-- Table `b2b`.`role_privilege_rel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b2b`.`role_privilege_rel` ;

CREATE TABLE IF NOT EXISTS `b2b`.`role_privilege_rel` (
  `role_privilege_id` BIGINT(10) NOT NULL AUTO_INCREMENT COMMENT '角色权限ID',
  `role_id` BIGINT(10) NULL COMMENT '角色ID',
  `privilege_id` BIGINT(10) NULL COMMENT '权限ID',
  `del_flag` TINYINT NOT NULL COMMENT '是否删除标志 0：否，1：是',
  `create_time` DATETIME NULL COMMENT '创建时间',
  `create_person` VARCHAR(32) NULL COMMENT '创建人',
  `update_time` DATETIME NULL COMMENT '修改时间',
  `update_person` VARCHAR(32) NULL COMMENT '修改人',
  `delete_time` DATETIME NULL COMMENT '删除时间',
  `delete_person` VARCHAR(32) NULL COMMENT '删除人',
  PRIMARY KEY (`role_privilege_id`),
  UNIQUE INDEX `role_privilege_id_UNIQUE` (`role_privilege_id` ASC))
ENGINE = InnoDB
COMMENT = '角色权限表';


-- -----------------------------------------------------
-- Table `b2b`.`table1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b2b`.`table1` ;

CREATE TABLE IF NOT EXISTS `b2b`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b2b`.`boss_api`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `b2b`.`boss_api` ;

CREATE TABLE IF NOT EXISTS `b2b`.`boss_api` (
  `boss_api_id` VARCHAR(45) NOT NULL,
  `api_path` VARCHAR(45) NULL COMMENT 'api路径',
  `api_http_type` VARCHAR(45) NULL COMMENT 'api请求类型',
  `previlege_id` VARCHAR(45) NULL,
  PRIMARY KEY (`boss_api_id`),
  UNIQUE INDEX `boss_api_id_UNIQUE` (`boss_api_id` ASC))
ENGINE = InnoDB
COMMENT = '请求api';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
