use `sbc-message`;
INSERT INTO `message_send_node`(`id`, `node_name`, `node_title`, `node_content`, `status`, `create_time`, `create_person`, `update_time`, `update_person`, `del_flag`, `send_sum`, `open_sum`, `route_name`, `node_type`, `node_code`) VALUES (20, '登录密码试错通知', '登录密码试错通知', '您的密码已连续3次错误，请注意账户安全，您可以使用动态密码登录商城或重置密码', 1, '2020-02-05 10:50:00', NULL, NULL, NULL, 0, 0, 0, NULL, 0, 'LOGIN_PASSWORD_SUM_OUT');
INSERT INTO `message_send_node`(`id`, `node_name`, `node_title`, `node_content`, `status`, `create_time`, `create_person`, `update_time`, `update_person`, `del_flag`, `send_sum`, `open_sum`, `route_name`, `node_type`, `node_code`) VALUES (21, '支付密码试错通知', '支付密码试错通知', '您的支付密码已连续3次错误，请注意账户安全，您可以登录商城重置密码', 1, '2020-02-05 10:50:00', NULL, NULL, NULL, 0, 0, 0, NULL, 0, 'PAY_PASSWORD_SUM_OUT');
INSERT INTO `message_send_node`(`id`, `node_name`, `node_title`, `node_content`, `status`, `create_time`, `create_person`, `update_time`, `update_person`, `del_flag`, `send_sum`, `open_sum`, `route_name`, `node_type`, `node_code`) VALUES (22, '优惠券到账提醒', '优惠券到账提醒', '您有{当天到账优惠券张数}张优惠券到账，优惠总额{优惠面值总额}，赶紧花掉他们吧~戳此查看>', 1, '2020-02-05 10:50:00', NULL, NULL, NULL, 0, 0, 0, NULL, 1, 'COUPON_RECEIPT');
INSERT INTO `message_send_node`(`id`, `node_name`, `node_title`, `node_content`, `status`, `create_time`, `create_person`, `update_time`, `update_person`, `del_flag`, `send_sum`, `open_sum`, `route_name`, `node_type`, `node_code`) VALUES (23, '优惠券过期提醒', '优惠券过期提醒', '您有{当天到账优惠券张数}张优惠券今日到期，优惠总额{优惠面值总额}，赶紧花掉他们吧~戳此查看>', 1, '2020-02-05 10:50:00', NULL, NULL, NULL, 0, 0, 0, NULL, 1, 'COUPON_EXPIRED');
INSERT INTO `message_send_node`(`id`, `node_name`, `node_title`, `node_content`, `status`, `create_time`, `create_person`, `update_time`, `update_person`, `del_flag`, `send_sum`, `open_sum`, `route_name`, `node_type`, `node_code`) VALUES (24, '积分到账提醒', '积分到账提醒', '您今日到账{当天到账积分数}积分，积分可以抵现金哦，真的很棒棒呢~戳此查看>', 1, '2020-02-05 10:50:00', NULL, NULL, NULL, 0, 0, 0, NULL, 1, 'INTEGRAL_RECEIPT');
INSERT INTO `message_send_node`(`id`, `node_name`, `node_title`, `node_content`, `status`, `create_time`, `create_person`, `update_time`, `update_person`, `del_flag`, `send_sum`, `open_sum`, `route_name`, `node_type`, `node_code`) VALUES (25, '积分过期提醒', '积分过期提醒', '您有{7天后过期积分数}将于7天后过期，积分来之不易，赶紧花掉他们吧~戳此查看>', 1, '2020-02-05 10:50:00', NULL, NULL, NULL, 0, 0, 0, NULL, 1, 'INTEGRAL_EXPIRED');
INSERT INTO `message_send_node`(`id`, `node_name`, `node_title`, `node_content`, `status`, `create_time`, `create_person`, `update_time`, `update_person`, `del_flag`, `send_sum`, `open_sum`, `route_name`, `node_type`, `node_code`) VALUES (26, '积分过期再次提醒', '积分过期再次提醒', '您有{当天过期积分数}今天过期，积分来之不易，赶紧花掉他们吧~戳此查看>', 1, '2020-02-05 10:50:00', NULL, NULL, NULL, 0, 0, 0, NULL, 1, 'INTEGRAL_EXPIRED_AGAIN');
INSERT INTO `message_send_node`(`id`, `node_name`, `node_title`, `node_content`, `status`, `create_time`, `create_person`, `update_time`, `update_person`, `del_flag`, `send_sum`, `open_sum`, `route_name`, `node_type`, `node_code`) VALUES (27, '成长值到账提醒', '成长值到账提醒', '您今日收获了{当天到账积分数}成长值，真的很棒棒呢~戳此查看>', 1, '2020-02-05 10:50:00', NULL, NULL, NULL, 0, 0, 0, NULL, 1, 'GROWTH_VALUE_RECEIPT');
INSERT INTO `message_send_node`(`id`, `node_name`, `node_title`, `node_content`, `status`, `create_time`, `create_person`, `update_time`, `update_person`, `del_flag`, `send_sum`, `open_sum`, `route_name`, `node_type`, `node_code`) VALUES (28, '余额账户变更提醒', '余额账户变更提醒', '您的余额账户今日收入{收入金额}，支出{支出金额}，如遇异常变动，请及时联系我们哦~点击查看明细>', 1, '2020-02-05 10:50:00', NULL, NULL, NULL, 0, 0, 0, NULL, 1, 'BALANCE_CHANGE');
INSERT INTO `message_send_node`(`id`, `node_name`, `node_title`, `node_content`, `status`, `create_time`, `create_person`, `update_time`, `update_person`, `del_flag`, `send_sum`, `open_sum`, `route_name`, `node_type`, `node_code`) VALUES (29, '提现申请提交成功通知', '提现申请提交成功通知', '您的提现申请已经提交成功，需要平台审核，请耐心等待哦~', 1, '2020-02-05 10:50:00', NULL, NULL, NULL, 0, 0, 0, NULL, 1, 'BALANCE_WITHDRAW_APPLY_FOR');
INSERT INTO `message_send_node`(`id`, `node_name`, `node_title`, `node_content`, `status`, `create_time`, `create_person`, `update_time`, `update_person`, `del_flag`, `send_sum`, `open_sum`, `route_name`, `node_type`, `node_code`) VALUES (30, '提现成功通知', '提现成功通知', '恭喜您，您的提现申请已处理成功，将在1-3工作日内到账~', 1, '2020-02-05 10:50:00', NULL, NULL, NULL, 0, 0, 0, NULL, 1, 'BALANCE_WITHDRAW_SUCCESS');
INSERT INTO `message_send_node`(`id`, `node_name`, `node_title`, `node_content`, `status`, `create_time`, `create_person`, `update_time`, `update_person`, `del_flag`, `send_sum`, `open_sum`, `route_name`, `node_type`, `node_code`) VALUES (31, '提现申请驳回通知', '提现申请驳回通知', '很抱歉，您的提现申请被驳回，原因是：{驳回原因}，点击查看>', 1, '2020-02-05 10:50:00', NULL, NULL, NULL, 0, 0, 0, NULL, 1, 'BALANCE_WITHDRAW_REJECT');
INSERT INTO `message_send_node`(`id`, `node_name`, `node_title`, `node_content`, `status`, `create_time`, `create_person`, `update_time`, `update_person`, `del_flag`, `send_sum`, `open_sum`, `route_name`, `node_type`, `node_code`) VALUES (32, '推广订单支付成功通知', '推广订单支付成功通知', '亲爱的{设置的分销员称呼}，您的推广订单{订单第一行商品名称}已支付成功，预计可赚{该笔订单待入账邀新奖励金额}，继续加油哦~点击查看>', 1, '2020-02-05 10:50:00', NULL, NULL, NULL, 0, 0, 0, NULL, 4, 'PROMOTE_ORDER_PAY_SUCCESS');
INSERT INTO `message_send_node`(`id`, `node_name`, `node_title`, `node_content`, `status`, `create_time`, `create_person`, `update_time`, `update_person`, `del_flag`, `send_sum`, `open_sum`, `route_name`, `node_type`, `node_code`) VALUES (33, '好友注册成功通知【无邀新奖励限制时】', '好友注册成功通知', '亲爱的{设置的分销员称呼}，您邀请的好友{手机号中四位掩码}已成功注册，{现金奖励金额}现金奖励，{优惠券奖励的总面额}优惠券奖励即将到账，继续加油哦~点击查看>', 1, '2020-02-05 10:50:00', NULL, NULL, NULL, 0, 0, 0, NULL, 4, 'FRIEND_REGISTER_SUCCESS_NO_REWARD');
INSERT INTO `message_send_node`(`id`, `node_name`, `node_title`, `node_content`, `status`, `create_time`, `create_person`, `update_time`, `update_person`, `del_flag`, `send_sum`, `open_sum`, `route_name`, `node_type`, `node_code`) VALUES (34, '好友注册成功通知【有邀新奖励限制时】', '好友注册成功通知', '亲爱的{设置的分销员称呼}，您邀请的好友{手机号中四位掩码}已成功注册，好友成功完成一笔订单就可获得{现金奖励金额}现金奖励，{优惠券奖励的总面额}优惠券奖励，继续加油哦~点击查看>', 1, '2020-02-05 10:50:00', NULL, NULL, NULL, 0, 0, 0, NULL, 4, 'FRIEND_REGISTER_SUCCESS_HAS_REWARD');
INSERT INTO `message_send_node`(`id`, `node_name`, `node_title`, `node_content`, `status`, `create_time`, `create_person`, `update_time`, `update_person`, `del_flag`, `send_sum`, `open_sum`, `route_name`, `node_type`, `node_code`) VALUES (35, '邀新奖励到账通知【有邀新奖励限制时】', '邀新奖励到账通知', '亲爱的{设置的分销员称呼}，您邀请的好友{手机号中四位掩码}已成功完成了一笔订单，{现金奖励金额}现金奖励，{优惠券奖励的总面额}优惠券奖励即将到账，继续加油哦~点击查看>', 1, '2020-02-05 10:50:00', NULL, NULL, NULL, 0, 0, 0, NULL, 4, 'INVITE_CUSTOMER_REWARD_RECEIPT');

INSERT INTO `push_send_node`(`id`, `node_name`, `node_type`, `node_code`, `node_title`, `node_context`, `expected_send_count`, `actually_send_count`, `open_count`, `status`, `del_flag`, `create_person`, `create_time`, `update_person`, `update_time`) VALUES (20, '登录密码试错通知', 0, 'LOGIN_PASSWORD_SUM_OUT', '登录密码试错通知', '您的密码已连续3次错误，请注意账户安全，您可以使用动态密码登录商城或重置密码', 0, 0, 0, 1, 0, NULL, NULL, '2c8080815cd3a74a015cd3ae86850001', '2020-02-06 02:00:06');
INSERT INTO `push_send_node`(`id`, `node_name`, `node_type`, `node_code`, `node_title`, `node_context`, `expected_send_count`, `actually_send_count`, `open_count`, `status`, `del_flag`, `create_person`, `create_time`, `update_person`, `update_time`) VALUES (21, '支付密码试错通知', 0, 'PAY_PASSWORD_SUM_OUT', '支付密码试错通知', '您的支付密码已连续3次错误，请注意账户安全，您可以登录商城重置密码', 0, 0, 0, 1, 0, NULL, NULL, '2c8080815cd3a74a015cd3ae86850001', '2020-02-06 02:00:06');
INSERT INTO `push_send_node`(`id`, `node_name`, `node_type`, `node_code`, `node_title`, `node_context`, `expected_send_count`, `actually_send_count`, `open_count`, `status`, `del_flag`, `create_person`, `create_time`, `update_person`, `update_time`) VALUES (22, '优惠券到账提醒', 1, 'COUPON_RECEIPT', '优惠券到账提醒', '您有{当天到账优惠券张数}张优惠券到账，优惠总额{优惠面值总额}，赶紧花掉他们吧~戳此查看>', 0, 0, 0, 1, 0, NULL, NULL, NULL, '2020-02-08 02:00:05');
INSERT INTO `push_send_node`(`id`, `node_name`, `node_type`, `node_code`, `node_title`, `node_context`, `expected_send_count`, `actually_send_count`, `open_count`, `status`, `del_flag`, `create_person`, `create_time`, `update_person`, `update_time`) VALUES (23, '优惠券过期提醒', 1, 'COUPON_EXPIRED', '优惠券过期提醒', '您有{当天到账优惠券张数}张优惠券今日到期，优惠总额{优惠面值总额}，赶紧花掉他们吧~戳此查看>', 0, 0, 0, 1, 0, NULL, NULL, NULL, '2020-02-08 02:00:05');
INSERT INTO `push_send_node`(`id`, `node_name`, `node_type`, `node_code`, `node_title`, `node_context`, `expected_send_count`, `actually_send_count`, `open_count`, `status`, `del_flag`, `create_person`, `create_time`, `update_person`, `update_time`) VALUES (24, '积分到账提醒', 1, 'INTEGRAL_RECEIPT', '积分到账提醒', '您今日到账{当天到账积分数}积分，积分可以抵现金哦，真的很棒棒呢~戳此查看>', 0, 0, 0, 1, 0, NULL, NULL, NULL, '2020-02-08 02:00:05');
INSERT INTO `push_send_node`(`id`, `node_name`, `node_type`, `node_code`, `node_title`, `node_context`, `expected_send_count`, `actually_send_count`, `open_count`, `status`, `del_flag`, `create_person`, `create_time`, `update_person`, `update_time`) VALUES (25, '积分过期提醒', 1, 'INTEGRAL_EXPIRED', '积分过期提醒', '您有{7天后过期积分数}将于7天后过期，积分来之不易，赶紧花掉他们吧~戳此查看>', 0, 0, 0, 1, 0, NULL, NULL, NULL, '2020-02-08 02:00:05');
INSERT INTO `push_send_node`(`id`, `node_name`, `node_type`, `node_code`, `node_title`, `node_context`, `expected_send_count`, `actually_send_count`, `open_count`, `status`, `del_flag`, `create_person`, `create_time`, `update_person`, `update_time`) VALUES (26, '积分过期再次提醒', 1, 'INTEGRAL_EXPIRED_AGAIN', '积分过期再次提醒', '您有{当天过期积分数}今天过期，积分来之不易，赶紧花掉他们吧~戳此查看>', 0, 0, 0, 1, 0, NULL, NULL, NULL, '2020-02-07 02:00:08');
INSERT INTO `push_send_node`(`id`, `node_name`, `node_type`, `node_code`, `node_title`, `node_context`, `expected_send_count`, `actually_send_count`, `open_count`, `status`, `del_flag`, `create_person`, `create_time`, `update_person`, `update_time`) VALUES (27, '成长值到账提醒', 1, 'GROWTH_VALUE_RECEIPT', '成长值到账提醒', '您今日收获了{当天到账积分数}成长值，真的很棒棒呢~戳此查看>', 0, 0, 0, 1, 0, NULL, NULL, NULL, '2020-02-07 02:00:08');
INSERT INTO `push_send_node`(`id`, `node_name`, `node_type`, `node_code`, `node_title`, `node_context`, `expected_send_count`, `actually_send_count`, `open_count`, `status`, `del_flag`, `create_person`, `create_time`, `update_person`, `update_time`) VALUES (28, '余额账户变更提醒', 1, 'BALANCE_CHANGE', '余额账户变更提醒', '您的余额账户今日收入{收入金额}，支出{支出金额}，如遇异常变动，请及时联系我们哦~点击查看明细>', 0, 0, 0, 1, 0, NULL, NULL, NULL, '2020-02-07 02:00:08');
INSERT INTO `push_send_node`(`id`, `node_name`, `node_type`, `node_code`, `node_title`, `node_context`, `expected_send_count`, `actually_send_count`, `open_count`, `status`, `del_flag`, `create_person`, `create_time`, `update_person`, `update_time`) VALUES (29, '提现申请提交成功通知', 1, 'BALANCE_WITHDRAW_APPLY_FOR', '提现申请提交成功通知', '您的提现申请已经提交成功，需要平台审核，请耐心等待哦~', 0, 0, 0, 1, 0, NULL, NULL, NULL, '2020-02-09 02:00:01');
INSERT INTO `push_send_node`(`id`, `node_name`, `node_type`, `node_code`, `node_title`, `node_context`, `expected_send_count`, `actually_send_count`, `open_count`, `status`, `del_flag`, `create_person`, `create_time`, `update_person`, `update_time`) VALUES (30, '提现成功通知', 1, 'BALANCE_WITHDRAW_SUCCESS', '提现成功通知', '恭喜您，您的提现申请已处理成功，将在1-3工作日内到账~', 0, 0, 0, 1, 0, NULL, NULL, NULL, '2020-02-09 02:00:01');
INSERT INTO `push_send_node`(`id`, `node_name`, `node_type`, `node_code`, `node_title`, `node_context`, `expected_send_count`, `actually_send_count`, `open_count`, `status`, `del_flag`, `create_person`, `create_time`, `update_person`, `update_time`) VALUES (31, '提现申请驳回通知', 1, 'BALANCE_WITHDRAW_REJECT', '提现申请驳回通知', '很抱歉，您的提现申请被驳回，原因是：{驳回原因}，点击查看>', 0, 0, 0, 1, 0, NULL, NULL, NULL, '2020-02-09 02:00:01');
INSERT INTO `push_send_node`(`id`, `node_name`, `node_type`, `node_code`, `node_title`, `node_context`, `expected_send_count`, `actually_send_count`, `open_count`, `status`, `del_flag`, `create_person`, `create_time`, `update_person`, `update_time`) VALUES (32, '推广订单支付成功通知', 4, 'PROMOTE_ORDER_PAY_SUCCESS', '推广订单支付成功通知', '亲爱的{设置的分销员称呼}，您的推广订单{订单第一行商品名称}已支付成功，预计可赚{该笔订单待入账邀新奖励金额}，继续加油哦~点击查看>', 0, 0, 0, 1, 0, NULL, NULL, NULL, '2020-02-11 02:00:04');
INSERT INTO `push_send_node`(`id`, `node_name`, `node_type`, `node_code`, `node_title`, `node_context`, `expected_send_count`, `actually_send_count`, `open_count`, `status`, `del_flag`, `create_person`, `create_time`, `update_person`, `update_time`) VALUES (33, '好友注册成功通知【无邀新奖励限制时】', 4, 'FRIEND_REGISTER_SUCCESS_NO_REWAR', '好友注册成功通知', '亲爱的{设置的分销员称呼}，您邀请的好友{手机号中四位掩码}已成功注册，{现金奖励金额}现金奖励，{优惠券奖励的总面额}优惠券奖励即将到账，继续加油哦~点击查看>', 0, 0, 0, 1, 0, NULL, NULL, NULL, NULL);
INSERT INTO `push_send_node`(`id`, `node_name`, `node_type`, `node_code`, `node_title`, `node_context`, `expected_send_count`, `actually_send_count`, `open_count`, `status`, `del_flag`, `create_person`, `create_time`, `update_person`, `update_time`) VALUES (34, '好友注册成功通知【有邀新奖励限制时】', 4, 'FRIEND_REGISTER_SUCCESS_HAS_REWA', '好友注册成功通知', '亲爱的{设置的分销员称呼}，您邀请的好友{手机号中四位掩码}已成功注册，好友成功完成一笔订单就可获得{现金奖励金额}现金奖励，{优惠券奖励的总面额}优惠券奖励，继续加油哦~点击查看>', 0, 0, 0, 1, 0, NULL, NULL, NULL, NULL);
INSERT INTO `push_send_node`(`id`, `node_name`, `node_type`, `node_code`, `node_title`, `node_context`, `expected_send_count`, `actually_send_count`, `open_count`, `status`, `del_flag`, `create_person`, `create_time`, `update_person`, `update_time`) VALUES (35, '邀新奖励到账通知【有邀新奖励限制时】', 4, 'INVITE_CUSTOMER_REWARD_RECEIPT', '邀新奖励到账通知', '亲爱的{设置的分销员称呼}，您邀请的好友{手机号中四位掩码}已成功完成了一笔订单，{现金奖励金额}现金奖励，{优惠券奖励的总面额}优惠券奖励即将到账，继续加油哦~点击查看>', 0, 0, 0, 1, 0, NULL, NULL, NULL, '2020-02-11 02:00:04');

ALTER TABLE `message_send` ADD COLUMN `plan_id` bigint(11)  NULL COMMENT '运营计划id';
ALTER TABLE `message_send` ADD COLUMN `route_params` varchar(255) NULL COMMENT '落地页参数';

ALTER TABLE `push_send` ADD COLUMN `plan_id` bigint(20)  NULL COMMENT '运营计划id';
ALTER TABLE `push_detail` ADD COLUMN `plan_id` bigint(20)  NULL COMMENT '运营计划id';

-- push_detail 表plan_id加索引
ALTER TABLE `push_detail` ADD INDEX `plan_id_index`(`plan_id`) USING BTREE COMMENT '运营计划id索引';

use `xxl-job`;
INSERT INTO `xxl_job_qrtz_trigger_info`(`id`, `job_group`, `job_cron`, `job_desc`, `add_time`, `update_time`, `author`, `alarm_email`, `executor_route_strategy`, `executor_handler`, `executor_param`, `executor_block_strategy`, `executor_timeout`, `executor_fail_retry_count`, `glue_type`, `glue_source`, `glue_remark`, `glue_updatetime`, `child_jobid`) VALUES (71, 1, '0 0 19 * * ?', '优惠券、积分、成长值通知节点定时任务', '2020-02-12 11:48:10', '2020-02-12 11:48:10', '许云鹏', '', 'FIRST', 'CouponAndIntegralMessageJobHandler', '', 'SERIAL_EXECUTION', 0, 0, 'BEAN', '', 'GLUE代码初始化', '2020-02-12 11:48:10', '');
INSERT INTO `xxl_job_qrtz_trigger_info`(`id`, `job_group`, `job_cron`, `job_desc`, `add_time`, `update_time`, `author`, `alarm_email`, `executor_route_strategy`, `executor_handler`, `executor_param`, `executor_block_strategy`, `executor_timeout`, `executor_fail_retry_count`, `glue_type`, `glue_source`, `glue_remark`, `glue_updatetime`, `child_jobid`) VALUES (72, 1, '0 0 9 * * ?', '积分过期再次提醒定时任务', '2020-02-12 11:48:58', '2020-02-12 11:48:58', '许云鹏', '', 'FIRST', 'IntegralMessageJobHandler', '', 'SERIAL_EXECUTION', 0, 0, 'BEAN', '', 'GLUE代码初始化', '2020-02-12 11:48:58', '');

